name: healthiee
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  flutter_spinkit: ^5.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1  
  firebase_storage: ^8.0.0
  fluttertoast: ^8.0.3
  flutter_awesome_alert_box: ^1.0.1
  file_picker: ^1.5.1
  flutter_downloader: ^1.5.2
  dio: ^4.0.0
  permission_handler: ^6.1.1
  path_provider: ^2.0.1
  ext_storage: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Pacifico     
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Kanit     
      fonts:
        - asset: fonts/Kanit.ttf
  assets:
    - images/
  uses-material-design: true

